### ISSUE TITLE
Dropdown behavior

### ISSUE THREAD

**Issue by simplecommerce** [kaoz70/grapesjs-blocks-bootstrap4#1]
Hi Miguel,

I noticed a strange behavior when importing the following code in the canvas.

```
<ul>
  <li class="dropdown"></li>
</ul>
```

This causes a crash, I had to wrap a try and catch around editor.setComponents in order to prevent it from breaking.

But if I do the following, it works

```
<ul>
  <li class="dropdown">test</li>
</ul>
```

Another thing I noticed, is that when I import the working code, it adds additional components.

Here is the result.

```
<ul>
  <li class="dropdown">test
    <a role="button" data-toggle="dropdown" aria-haspopup class="btn dropdown-toggle">Click to toggle</a>
    <div class="dropdown-menu">
      <h6 class="dropdown-header">Dropdown header
      </h6>
      <a class="dropdown-item">Dropdown item</a>
      <div class="dropdown-divider">
      </div>
      <a class="dropdown-item">Dropdown item</a>
    </div>
  </li>
</ul>
```

Is this normal behavior?

I am only asking because, when I import an old code from an existing website, since it wasn't built on bootstrap 4, in places where we have the dropdown class, it causes additional components to be inserted.

**Comment by kaoz70** [comment]
Hi Kheang,

I tested importing

    <ul>
      <li class="dropdown"></li>
    </ul>

But I did not get any errors, can you perhaps set up a demo for me to check?

Regarding the additional components created, this is the current behavior.

While using the "import" feature, I was not able to get GrapesJs to detect the parent component correctly so there's a bug there.

On a side note, I've updated the code so that you can collapse / expand the menu via the trait manager

**Comment by simplecommerce** [comment]
Hi Miguel,

You are right, I am not longer able to reproduce the error, I believe it might've been an out of date version which was fixed when you fixed both the Link and Dropdown components.

Nice touch for the trait to open or close the dropdown.

Thanks a bunch! :)
