### ISSUE TITLE
Issue Selecting PluginsOpts

### ISSUE THREAD

**Issue by afotey** [kaoz70/grapesjs-blocks-bootstrap4#3]
What is the correct syntax for determining which items to show on the right sidebar?

I tried to add them to what is shown here (Container, Row, Column, Column Break, Media Object, etc.) but it fails...

Please advise. 

Thanks!

![pluginsopts_selection](https://user-images.githubusercontent.com/485858/34365646-7dd17200-ea60-11e7-880c-2957d6cbd4ba.png)

**Comment by z1lk** [comment]
@afotey The above syntax looks ok. All blocks are included by default and so you do not need to explicitly require any of them. Are you testing with the default `index.html` or including the plugin elsewhere? Right now I'm only doing development and haven't tested the plugin in other environments, but still I appreciate your feedback.

**Comment by afotey** [comment]
Thanks for responding!

I'm testing with the default index.html file. 

What I'm looking to do is to show only specific parts of the Blocks area, specifically the Layout section. I'm looking to hide all the other parts.

Not entirely sure how to accomplish this; with the base plugins I usually invoke the Blocks components in the manner pictured in this particular manner with the gjs-plugin-forms section:

![screen shot 2017-12-27 at 1 48 31 pm](https://user-images.githubusercontent.com/485858/34390287-de4def76-eb0c-11e7-8820-259a089ccf24.png)

**Comment by z1lk** [comment]
I understand. The reason I didn't make the plugin config use that format is because there will be many blocks. If you wanted to exclude just one block, you'd have to type out all the other block names. You can exclude individual blocks as the readme indicates (key=block name, value=false). I've added another config option to easily achieve what you're trying to do. You can exclude all categories but the Layout category like this:

```js
pluginsOpts: {
  // ...
  'grapesjs-blocks-bootstrap4': {
    blocks: {},
    blockCategories: {
      components: false,
      typography: false,
      basic: false
    },
    labels: {},
    // ...
  }
  // ...
}
```

Hope this helps! As I said, I haven't tested thoroughly and there are no automated tests at this point, so please come back if you have more issues. I'm still learning Grapes/Backbone myself so there are bound to be some.

**Comment by afotey** [comment]
Thanks!

I'm off for the holidays. I'll try this and let you know how it works!

**Comment by kaoz70** [comment]
I'm closing this issue as it seems resolved.
