### ISSUE TITLE
Asset manager no longer opens for images when using this plugin

### ISSUE THREAD

**Issue by pmill** [kaoz70/grapesjs-blocks-bootstrap4#6]
Using the code in index.html, dragging and dropping an image block, then double-clicking it doesn't open the asset manager.

Removing this plugin makes this functionality work.

**Comment by taras-sarmat** [comment]
Is there any news about this issue?

**Comment by iainheng** [comment]
Suffered from the same issue. Any fix?

**Comment by write-software** [comment]
Distribution still appears to be broken

**Comment by gasserol** [comment]
Hi, solution/workaround for this issue: clone this repository, in src open up components.js and comment 
```
if (blocks.image) { ... }
```
starting at line 284. Then run npx webpack to generate a new grapesjs-blocks-bootstrap4.min.js in dist and use this instead of the original one. This disables the particular traits but it works with normal assetManager. It works also inside the card element.

**Comment by kaoz70** [comment]
Can anyone please check if the issue is resolved with version 0.1.15?

**Comment by kaoz70** [comment]
Closing this since its seems to be solved.
